### PR TITLE
💥 Build using N-API instead of NAN

### LINKED ISSUE #4: Failed to build with Node v12
I am using this library in a node 10 project and works fine.
However I am going to migrate to NodeJS 12 and I am stuck with this library because it does not compile:

```
> lodepng@1.2.0 install /webmail/node_modules/lodepng
> node-gyp rebuild

make: Entering directory '/webmail/node_modules/lodepng/build'
  CXX(target) Release/obj.target/lodepng/vendor/lodepng.o
  CXX(target) Release/obj.target/lodepng/src/decode.o
In file included from ../../nan/nan_converters.h:67:0,
                 from ../../nan/nan.h:202,
                 from ../src/decode.cc:2:
../../nan/nan_converters_43_inl.h: In static member function 'static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)':
../../nan/nan_converters_43_inl.h:18:51: warning: 'v8::MaybeLocal<v8::Boolean> v8::Value::ToBoolean(v8::Local<v8::Context>) const' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
       val->To ## TYPE(isolate->GetCurrentContext())                            \
                                                   ^
../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro 'X'
 X(Boolean)
 ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:2568:59: note: declared here
                 V8_WARN_UNUSED_RESULT MaybeLocal<Boolean> ToBoolean(
                                                           ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_converters.h:67:0,
                 from ../../nan/nan.h:202,
                 from ../src/decode.cc:2:
../../nan/nan_converters_43_inl.h: In static member function 'static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)':
../../nan/nan_converters_43_inl.h:37:57: warning: 'v8::Maybe<bool> v8::Value::BooleanValue(v8::Local<v8::Context>) const' is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
   return val->NAME ## Value(isolate->GetCurrentContext());                     \
                                                         ^
../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro 'X'
 X(bool, Boolean)
 ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:2606:51: note: declared here
                 V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                   ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../src/decode.cc:2:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)':
../../nan/nan_implementation_12_inl.h:105:32: error: no matching function for call to 'v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)'
                           , obj));
                                ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:4170:31: note: candidate: static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)
   static MaybeLocal<Function> New(
                               ^~~
/root/.cache/node-gyp/12.13.0/include/node/v8.h:4170:31: note:   no known conversion for argument 1 from 'v8::Isolate*' to 'v8::Local<v8::Context>'
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../src/decode.cc:2:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)':
../../nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to 'v8::StringObject::New(v8::Local<v8::String>&)'
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:5426:23: note: candidate: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)
   static Local<Value> New(Isolate* isolate, Local<String> value);
                       ^~~
/root/.cache/node-gyp/12.13.0/include/node/v8.h:5426:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../src/decode.cc:2:
../../nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before '>' token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                          ^
../../nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ')' token
   return v8::StringObject::New(value).As<v8::StringObject>();
                                                            ^
In file included from ../src/decode.cc:2:0:
../../nan/nan.h: In constructor 'Nan::Utf8String::Utf8String(v8::Local<v8::Value>)':
../../nan/nan.h:1034:53: error: no matching function for call to 'v8::Value::ToString()'
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:2572:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/root/.cache/node-gyp/12.13.0/include/node/v8.h:2572:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:2588:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.cache/node-gyp/12.13.0/include/node/v8.h:2588:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/decode.cc:2:0:
../../nan/nan.h:1044:74: error: no matching function for call to 'v8::String::WriteUtf8(char*&, int, int, const int&)'
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:2782:7: note: candidate: int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/root/.cache/node-gyp/12.13.0/include/node/v8.h:2782:7: note:   no known conversion for argument 1 from 'char*' to 'v8::Isolate*'
In file included from ../src/decode.cc:2:0:
../../nan/nan.h: In member function 'void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)':
../../nan/nan.h:1818:64: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                                                                ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:3403:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/decode.cc:2:0:
../../nan/nan.h: In member function 'void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)':
../../nan/nan.h:1824:42: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)->Set(key, value);
                                          ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:3403:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/decode.cc:2:0:
../../nan/nan.h: In member function 'void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)':
../../nan/nan.h:1830:44: warning: 'bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)->Set(index, value);
                                            ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:3412:22: note: declared here
                 bool Set(uint32_t index, Local<Value> value));
                      ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/decode.cc:2:0:
../../nan/nan.h: In member function 'v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const':
../../nan/nan.h:1836:61: warning: 'v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
         New(persistentHandle)->Get(New(key).ToLocalChecked()));
                                                             ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:3457:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/decode.cc:2:0:
../../nan/nan.h: In member function 'v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const':
../../nan/nan.h:1842:55: warning: 'v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(New(persistentHandle)->Get(key));
                                                       ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:3457:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/decode.cc:2:0:
../../nan/nan.h: In member function 'v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const':
../../nan/nan.h:1847:57: warning: 'v8::Local<v8::Value> v8::Object::Get(uint32_t)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(New(persistentHandle)->Get(index));
                                                         ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:3461:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
                                                   ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from /usr/include/c++/6/cassert:44:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:53,
                 from ../src/decode.cc:2:
../../nan/nan_object_wrap.h: In destructor 'virtual Nan::ObjectWrap::~ObjectWrap()':
../../nan/nan_object_wrap.h:24:25: error: 'class Nan::Persistent<v8::Object>' has no member named 'IsNearDeath'
     assert(persistent().IsNearDeath());
                         ^
In file included from ../../nan/nan.h:2657:0,
                 from ../src/decode.cc:2:
../../nan/nan_object_wrap.h: In member function 'void Nan::ObjectWrap::MakeWeak()':
../../nan/nan_object_wrap.h:67:34: warning: 'void v8::PersistentBase<T>::MarkIndependent() [with T = v8::Object]' is deprecated: Weak objects are always considered independent. Use TracedGlobal when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive. [-Wdeprecated-declarations]
     persistent().MarkIndependent();
                                  ^
In file included from /root/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /root/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../src/decode.cc:1:
/root/.cache/node-gyp/12.13.0/include/node/v8.h:567:22: note: declared here
       V8_INLINE void MarkIndependent());
                      ^
/root/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from /usr/include/c++/6/cassert:44:0,
                 from /root/.cache/node-gyp/12.13.0/include/node/node_object_wrap.h:26,
                 from ../../nan/nan.h:53,
                 from ../src/decode.cc:2:
../../nan/nan_object_wrap.h: In static member function 'static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)':
../../nan/nan_object_wrap.h:124:26: error: 'class Nan::Persistent<v8::Object>' has no member named 'IsNearDeath'
     assert(wrap->handle_.IsNearDeath());
                          ^
../src/decode.cc: In member function 'virtual void DecodeWorker::HandleOKCallback()':
../src/decode.cc:34:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/decode.cc:2:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
lodepng.target.mk:114: recipe for target 'Release/obj.target/lodepng/src/decode.o' failed
make: Leaving directory '/webmail/node_modules/lodepng/build'
make: *** [Release/obj.target/lodepng/src/decode.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /webmail/node_modules/lodepng
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN webmail-back-end@1.0.0 No description
npm WARN webmail-back-end@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lodepng@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lodepng@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-31T09_27_51_876Z-debug.log
```

I see there is a pull request pending which should support Node v12.
Can you review and eventually accept it?
Thanks!

### PR DESCRIPTION
**Pull request by LinusU**
To do:
- [x] Update migration guide to mention new input & output
- [x] Use `napi_create_reference`/`napi_delete_reference` to keep reference to data during work

Fixes: #4

### CODE REVIEW

**Comment by LinusU** [comment]
Should be all done now!

@bermi @matteomattei if you want to help test this it would be great! Just install it with `npm install LinusU/node-lodepng#napi` and let me know if it works in your project ☺️ 

edit: note the following migration guide:

Migration Guide:

- Upgrade to at least Node.js 8.6.0 for continued support.
- The `data` parameter to `encode` does no longer accept 16-bit, 32-bit, or float arrays.
- The output from `decode` is now an instance of `ImageData`, meaning that `data` is an `Uint8ClampedArray`.

**Comment by LinusU** [comment]
Seems to be working great, releasing 🚀

**Comment by bermi** [comment]
👏Thank you @LinusU! Will give it a shot next week and will let you know if I run into issues

**Comment by matteomattei** [comment]
Thanks! I will test it next week and I will let you know

**Pull request merged**
