### PR TITLE
Add support for node 8 to 12

### PR DESCRIPTION
**Pull request by bermi**
This change upgrades npm dependencies, lodepng version and allows running `node-lodepng` from node 6 to node 12.

Running the tests require node 8

### CODE REVIEW

**Comment by matteomattei** [comment]
I didn't test, but if it works with node 12, it is exactly what I need!
Can the package owner verify, accept and merge it?

**Comment by LinusU** [comment]
Sorry for the delay on this!

I'm going to convert this project to use NAPI instead so it should be compatible with all versions of node, even without a rebuild 🙌 

I'll pull in your commit that updates LodePNG though so that you still get credited as a contributor. Thank you so much for the PR! ❤️

**Comment by LinusU** [comment]
Almost done with it here, will finish tomorrow: #6

**Comment by LinusU** [comment]
closing in favour of #6 ☺️

**Pull request closed without merging**
