### PR TITLE
Persisting handle to buffer, so it does not get garbage collected during png decoding

### PR DESCRIPTION
**Pull request by pdobrev**
Also, upgraded lodepng version.

### CODE REVIEW

**Comment by iboB** [comment]
This fixes issue #1

**Comment by LinusU** [comment]
Actually, the [documentation for Nan::AsyncWorker](https://github.com/nodejs/nan/blob/master/doc/asyncworker.md#nanasyncworker) suggests that we could just do `SaveToPersistent("data", data)`, would that be more nice?

Also, it would be very nice if we could add a test case for this, maybe with `--expose-gc`?

**Comment by pdobrev** [comment]
Using Nan is more idiomatic, you're right. I'll commit a version that uses that.

As for a test, running multiple decodes with `global.gc()` in the callbacks should do the trick. We have a 100% repro on an internal system that does a ton of .decodes() in parallel and I verified the fix on it.

**Comment by LinusU** [comment]
Nice 👍 

I just pulled in the new lodepng separately, could you rebase on master and squash? Thanks!

**Comment by pdobrev** [comment]
Done :)

**Comment by LinusU** [comment]
Thanks!

**Comment by LinusU** [comment]
Released as 0.2.2 👍

**Pull request merged**
