### PR TITLE
🎉 Upgrade lodepng to 20230410

### PR DESCRIPTION
**Pull request by vicb**
The performance is similar (see my benchmark below) but I guess it's good to have some fixes.
The change history is at the end of the header file.

Before

```
   @vivaxy/png  85.62 ms ±  1.55 %  (34 runs sampled)
    pngjs        74.09 ms ±  0.78 %  (38 runs sampled)
    lodepng       2.51 ms ±  1.70 %  (79 runs sampled)
```

After

```
Benchmarks:
  sample
    @vivaxy/png  85.56 ms ±  1.03 %  (34 runs sampled)
    pngjs        74.53 ms ±  0.70 %  (38 runs sampled)
    lodepng       2.53 ms ±  1.16 %  (81 runs sampled)
```

### CODE REVIEW

**Comment by vicb** [comment]
hey @LinusU anything I can help with to get this merged?

**Comment by vicb** [comment]
ping @LinusU :)

**Comment by vicb** [comment]
ping @LinusU :)

**Comment by LinusU** [comment]
@vicb very sorry for the super long delay on this! Thanks for the PR, merged and released 🚀 


[🚢 2.3.0 / 2024-09-11](https://github.com/LinusU/node-lodepng/releases/tag/v2.3.0)

**Pull request merged**
